### ISSUE TITLE
Clear miner predictions when it's deregistered

### ISSUE THREAD

**Issue by ultrashiny** [Nickel5-Inc/bettensor#49]
[`check_hotkeys`](https://github.com/Bettensor/bettensor/blob/main/bettensor/validator/bettensor_validator.py#L327) method in `bettensor_validator.py` detects changes in the hotkey list and clears scores for miners when they’re deregistered.
However, [`reset_miner`](https://github.com/Bettensor/bettensor/blob/main/bettensor/validator/utils/scoring/scoring.py#L531) method in `ScoringSystem` doesn’t remove stored prediction data in the database for deregistered miners/hotkeys, which means this data persists.

This might affect a hotkey's score if it gets registered again. I recommend making an update to handle this:
- Either remove all database records related to a miner when it’s deregistered,
- Or add a new column in the predictions table to indicate if the data is from a currently active miner or a deregistered one.

**Comment by ultrashiny** [comment]
i might be wrong and please correct me if i'm mistaken

**Comment by geardici** [comment]
apologies for the slow response, yes this is fixed now. Closing the issue

**Comment by ultrashiny** [comment]
no worries, great job, btw
